version: '3'
services:
  db-postgres-lifeHub:
    container_name: db-postgres-lifeHub
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'lifehub'
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - db-postgres-lifeHub:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres-lifeHub:5432/lifehub
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APPLICATION_SECURITY_JWT_SECRETKEY=${APPLICATION_SECURITY_JWT_SECRETKEY}
    depends_on:
      - db-postgres-lifeHub
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ./target:/app/target
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  db-postgres-lifeHub: {}
